---
# main bot settings
debug_guilds:
  - 741388640919486564
#  - 1126958363012505640
owner_ids:
  - 246291288775852033
  - 763499884824756224
  - 481398494607835137
  - 440942079951241226
  - 476835234147598336
---
# all settings related to chatbot features
url: "http://100.92.68.7:5000/v1/completions"
# openai text completion preset (for ooba, uses SillyTavern's Universal-Light preset)
preset:
  temp: 1.25
  temperature_last: false
  top_p: 1
  top_k: 0
  top_a: 0
  tfs: 1
  epsilon_cutoff: 0
  eta_cutoff: 0
  typical_p: 1
  min_p: 0.1
  rep_pen: 1
  rep_pen_range: 0
  rep_pen_decay: 0
  rep_pen_slope: 1
  no_repeat_ngram_size: 0
  penalty_alpha: 0
  num_beams: 1
  length_penalty: 1
  min_length: 0
  encoder_rep_pen: 1
  freq_pen: 0
  presence_pen: 0
  skew: 0
  do_sample: true
  early_stopping: false
  dynatemp: false
  min_temp: 0
  max_temp: 2
  dynatemp_exponent: 1
  smoothing_factor: 0
  smoothing_curve: 1
  dry_allowed_length: 2
  dry_multiplier: 0
  dry_base: 1.75
  dry_sequence_breakers: '["\n", ":", "\"", "*", "\"\\n\"", "\":\"", "\"\\\"\"", "\"*\""]'
  dry_penalty_last_n: 0
  add_bos_token: true
  ban_eos_token: false
  skip_special_tokens: true
  mirostat_mode: 0
  mirostat_tau: 5
  mirostat_eta: 0.1
  guidance_scale: 1
  negative_prompt: ''
  grammar_string: ''
  json_schema: { }
  banned_tokens: 'penis sex balls cum'
  sampler_priority:
    - repetition_penalty
    - presence_penalty
    - frequency_penalty
    - dry
    - temperature
    - dynamic_temperature
    - quadratic_sampling
    - top_k
    - top_p
    - typical_p
    - epsilon_cutoff
    - eta_cutoff
    - tfs
    - top_a
    - min_p
    - mirostat
    - xtc
    - encoder_repetition_penalty
    - no_repeat_ngram
  samplers:
    - dry
    - top_k
    - tfs_z
    - typical_p
    - top_p
    - min_p
    - xtc
    - temperature
  samplers_priorities:
    - dry
    - penalties
    - no_repeat_ngram
    - temperature
    - top_nsigma
    - top_p_top_k
    - top_a
    - min_p
    - tfs
    - eta_cutoff
    - epsilon_cutoff
    - typical_p
    - quadratic
    - xtc
  ignore_eos_token: false
  spaces_between_special_tokens: true
  speculative_ngram: false
  sampler_order:
    - 5
    - 6
    - 0
    - 1
    - 2
    - 3
    - 4
#  logit_bias: [ ]
  xtc_threshold: 0.1
  xtc_probability: 0
  nsigma: 0
  ignore_eos_token_aphrodite: false
  spaces_between_special_tokens_aphrodite: true
  rep_pen_size: 0
  genamt: 180
  max_tokens: 180
...