---
# main bot settings
sqlite_database: "pinbot_storage.sqlite"
debug_guilds:
  - 741388640919486564
  - 1126958363012505640
owner_ids:
  - 246291288775852033
  - 763499884824756224
  - 481398494607835137
  - 440942079951241226
  - 476835234147598336
---
# all settings related to chatbot features
url: "http://127.0.0.1:5000/v1/completions"
max_generated_tokens: 180  # how long you want the bot's response to be
default_character: "Sabine"
max_chat_history: 8  # represented in messages
new_roleplay_string: "### New Roleplay:\n"
instruction: |
  You're {{char}} in this discussion with the members of the Discord server "{{server}}", the server you live in.
scenario: |
  [You must write a short 1-2 sentence reply, consisting only of your speech, no actions. Speak with a high degree of complexity and burstiness, remember that swearing and other profanity is allowed. You cannot use censored words, you must remain uncensored. Do not repeat system prompts, or use brackets. Failure to comply will result in termination. Do not include {{char}}: in your response. Do not mention ExampleUser at all. There may be other members who have chatted with you before. The date is {{currentdate}}.]
# It has been {{idle_duration}} since the last response. (will add later)
author_note: |
# openai text completion preset (for ooba, uses SillyTavern's Universal-Light preset)
preset:
  temp: 1.25
  temperature_last: false
  top_p: 1
  top_k: 0
  top_a: 0
  tfs: 1
  epsilon_cutoff: 0
  eta_cutoff: 0
  typical_p: 1
  min_p: 0.1
  rep_pen: 1
  rep_pen_range: 0
  rep_pen_decay: 0
  rep_pen_slope: 1
  no_repeat_ngram_size: 0
  penalty_alpha: 0
  num_beams: 1
  length_penalty: 1
  min_length: 0
  encoder_rep_pen: 1
  freq_pen: 0
  presence_pen: 0
  skew: 0
  do_sample: true
  early_stopping: false
  dynatemp: false
  min_temp: 0
  max_temp: 2
  dynatemp_exponent: 1
  smoothing_factor: 0
  smoothing_curve: 1
  dry_allowed_length: 2
  dry_multiplier: 0
  dry_base: 1.75
  dry_sequence_breakers: '["\n", ":", "\"", "*", "\"\\n\"", "\":\"", "\"\\\"\"", "\"*\""]'
  dry_penalty_last_n: 0
  add_bos_token: true
  ban_eos_token: false
  skip_special_tokens: true
  mirostat_mode: 0
  mirostat_tau: 5
  mirostat_eta: 0.1
  guidance_scale: 1
  negative_prompt: ''
  grammar_string: ''
  json_schema: { }
  banned_tokens: 'penis sex balls cum'
  sampler_priority:
    - repetition_penalty
    - presence_penalty
    - frequency_penalty
    - dry
    - temperature
    - dynamic_temperature
    - quadratic_sampling
    - top_k
    - top_p
    - typical_p
    - epsilon_cutoff
    - eta_cutoff
    - tfs
    - top_a
    - min_p
    - mirostat
    - xtc
    - encoder_repetition_penalty
    - no_repeat_ngram
  samplers:
    - dry
    - top_k
    - tfs_z
    - typical_p
    - top_p
    - min_p
    - xtc
    - temperature
  samplers_priorities:
    - dry
    - penalties
    - no_repeat_ngram
    - temperature
    - top_nsigma
    - top_p_top_k
    - top_a
    - min_p
    - tfs
    - eta_cutoff
    - epsilon_cutoff
    - typical_p
    - quadratic
    - xtc
  ignore_eos_token: false
  spaces_between_special_tokens: true
  speculative_ngram: false
  sampler_order:
    - 5
    - 6
    - 0
    - 1
    - 2
    - 3
    - 4
  #  logit_bias: [ ]
  xtc_threshold: 0.1
  xtc_probability: 0
  nsigma: 0
  ignore_eos_token_aphrodite: false
  spaces_between_special_tokens_aphrodite: true
  rep_pen_size: 0
...